DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS film_genre;
DROP TABLE IF EXISTS likes;

DROP TABLE IF EXISTS films;
--DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS mpa;
DROP TABLE IF EXISTS users;


CREATE TABLE IF NOT EXISTS users(
    id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR,
    login       VARCHAR     UNIQUE NOT NULL,
    email       VARCHAR     UNIQUE,
    birthday    DATE        CHECK (birthday <= CURRENT_DATE)
);

CREATE TABLE IF NOT EXISTS genres (
    id      bigint         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR        NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa (
    id      bigint           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255)     NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    id              bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR         NOT NULL,
    description     VARCHAR(200),   CHECK (LENGTH(description) <= 200),
    release_date    DATE,
    duration        INT,
    genre           bigint,
    mpa             bigint,
    FOREIGN KEY (mpa) REFERENCES mpa(id)
);

CREATE TABLE IF NOT EXISTS friends (
    user_id     bigint,
    friend_id   bigint,
    approved    BOOLEAN,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (friend_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS likes (
    film_id     bigint,
    user_id     bigint,
    FOREIGN KEY (film_id) REFERENCES films(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id     bigint,
    genre_id    bigint,
    FOREIGN KEY (film_id) REFERENCES films(id),
    FOREIGN KEY (genre_id) REFERENCES genres(id)
);